/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <android/log.h>
#include <unistd.h>
#include <sys/inotify.h>
#include <fcntl.h>
#include "test.c"
//#include "facedetect.cpp"

#define LOGI(...) ((void)__android_log_print(ANDROID_LOG_INFO, "native", __VA_ARGS__))
#define LOGW(...) ((void)__android_log_print(ANDROID_LOG_WARN, "native", __VA_ARGS__))
#define LOGE(...) ((void)__android_log_print(ANDROID_LOG_ERROR, "native", __VA_ARGS__))

/* Header for class com_example_jnitest_NativeTest */

#ifndef _Included_com_example_jnitest_NativeTest
#define _Included_com_example_jnitest_NativeTest
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_example_jnitest_NativeTest
 * Method:    test
 * Signature: ()[B
 */
JNIEXPORT void JNICALL Java_com_example_jnitest_NativeTest_test(JNIEnv *env,
		jclass clz) {
	test();
}

#ifdef __cplusplus
}
#endif
#endif
